<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MailKit" Version="4.14.1" />
    <PackageVersion Include="MSTest" Version="4.0.2" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.14.1" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>
</Project>
