name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory artifacts/test-results
    - name: Test Results Upload
      uses: actions/upload-artifact@v5
      with:
          name: test-results
          path: "artifacts/test-results/"
          retention-days: 1
          if-no-files-found: error
